In [1]:
# Import many dataFrame for the Algorithm Comparison:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import cm
from matplotlib.lines import Line2D
from scipy import stats
import glob
import os
# pd.set_option('display.max_rows', 500)
from scipy.stats import gaussian_kde
from scipy.stats import sem
import seaborn as sns
from scipy.stats.mstats import winsorize

### Import our libraries
# some_file.py
import sys
# insert at 1, 0 is the script path (or '' in REPL)
sys.path.insert(1, '../data_preprocessing/')
import fixation_plots as plots
from utility import utilitiesCalc
import interpolationET as inter
counter = 21
lb_data = []
el_data = []
trial_data = []
targets_data = []
subject = 0
targets_data = []
el_blinks = pd.DataFrame()
el_blnk = []
s_gaze = 0
all_target = pd.DataFrame()
df_eyelink_raw = pd.DataFrame()
temp_blinks = []
temp_all_data = []
df_blinks_el = pd.DataFrame()
temp_raw_blinks = []
for i in range(1,counter):
    subject = subject + 1
    s_gaze = s_gaze + 1
    el_gaze = pd.read_csv("../data/el_data/p" + str(i) + '.csv', engine='python')
    el_blinks = pd.read_csv("../data/el_data/el_events/blinks/p" + str(i) + '_events.csv', engine='python')
    lb_gaze = pd.read_csv("../data/lb_data/timeseries_data/p" + str(i) + '_XYTC.csv', engine='python')
    print('loads files from =' + str(i))
    
   

    lb_gaze = utilitiesCalc.addParticipantNumberCol(subject, lb_gaze)
    lb_gaze = inter.formating_labvanced (lb_gaze)
    lb_gaze = lb_gaze[lb_gaze['Task_Name'] == "free_view"]
    
    
    el_gaze = utilitiesCalc.addParticipantNumberCol(subject, el_gaze)
    
    
    el_blinks = utilitiesCalc.addParticipantNumberCol(s_gaze, el_blinks)
    
         # Not enough targets detected Eyelink
    lb_gaze = lb_gaze[lb_gaze['Participant_Nr'] != 16]
    el_gaze = el_gaze[el_gaze['Participant_Nr'] != 16]
    el_blinks = el_blinks[el_blinks['Participant_Nr'] != 16]
    # Bad calibration Labvanced and lag
    lb_gaze = lb_gaze[lb_gaze['Participant_Nr'] != 17]
    el_gaze = el_gaze[el_gaze['Participant_Nr'] != 17]
    el_blinks = el_blinks[el_blinks['Participant_Nr'] != 17]
    # Delay between Labvanced 300hz and Eyelink 300hz resampled = -432504
    # Bad calibration Labvanced and lag 
    lb_gaze = lb_gaze[lb_gaze['Participant_Nr'] != 9]
    el_gaze = el_gaze[el_gaze['Participant_Nr'] != 9]
    el_blinks = el_blinks[el_blinks['Participant_Nr'] != 9]
    # Delay between Labvanced 300hz and Eyelink 300hz resampled = -68034
    # Bad calibration Labvanced and lag and # Not enough targets detected Eyetlink
    lb_gaze = lb_gaze[lb_gaze['Participant_Nr'] != 11]
    el_gaze = el_gaze[el_gaze['Participant_Nr'] != 11]
    el_blinks = el_blinks[el_blinks['Participant_Nr'] != 11]
    
    el = el_gaze.rename(columns={'X':'X_el','Y':'Y_el','Time':'t'})
    lb = lb_gaze.set_index('time_lb')
    
    
    el = el.set_index('t')
    
    def interpolation ():
    # Interpolate data

        df_temp = pd.concat([el, lb .index.to_frame()]).sort_index().interpolate()

        df_temp = df_temp[~df_temp.index.duplicated(keep='first')]
        df_interpolated = lb .merge(df_temp, left_index=True, right_index=True, how='left')

        df_interpolated = df_interpolated.drop(columns=['time_lb'])
        df_interpolated = df_interpolated.reset_index()

        return df_interpolated
    df_interpolated = interpolation()
    df_interpolated.reset_index(inplace=True)
    
    temp_all_data.append(df_interpolated)
    df = pd.concat(temp_all_data, axis=0, ignore_index=True)
    
    temp_blinks.append(el_blinks)
    df_eyelink_raw = pd.concat(temp_blinks, axis=0, ignore_index=True)
    
# #     temp_raw_blinks.append(df_blinks)

# #     df_blinks_el = pd.concat(temp_raw_blinks, axis=0, ignore_index=True)
# df.to_csv('../data/free_view_interpolated/free_view_inter.csv', index = False)

loads files from =1
loads files from =2
loads files from =3
loads files from =4
loads files from =5
loads files from =6
loads files from =7
loads files from =8
loads files from =9
loads files from =10
loads files from =11
loads files from =12
loads files from =13
loads files from =14
loads files from =15
loads files from =16
loads files from =17
loads files from =18
loads files from =19
loads files from =20

In [2]:
df_blinks_el

Empty DataFrame
Columns: []
Index: []

In [3]:
lb_gaze

,Block_Nr,Block_Name,Task_Nr,Task_Name,Trial_Nr,Trial_Id,Exp_Subject_Id,Rec_Session_Id,Session_Nr,timestamp,X_lb,Y_lb,time_lb,c,Participant_Nr
9585,1,block_1,7,free_view,1,4,451069,514401,1,1656920133773,641.640970,516.425711,1656920133747,1.00000,20
9586,1,block_1,7,free_view,1,4,451069,514401,1,1656920133846,651.426398,483.930950,1656920133785,1.00000,20
9587,1,block_1,7,free_view,1,4,451069,514401,1,1656920133872,639.011536,476.966259,1656920133851,1.00000,20
9588,1,block_1,7,free_view,1,4,451069,514401,1,1656920133901,676.132219,540.376215,1656920133885,1.00000,20
9589,1,block_1,7,free_view,1,4,451069,514401,1,1656920133944,696.353409,523.956871,1656920133918,1.00000,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11182,1,block_1,7,free_view,18,11,451069,514401,1,1656920233778,705.093527,510.103476,1656920233760,0.99797,20
11183,1,block_1,7,free_view,18,11,451069,514401,1,1656920233813,723.489640,449.186084,1656920233793,1.00000,20
11184,1,block_1,7,free_view,18,11,451069,514401,1,1656920233845,771.267121,466.154703,1656920233826,1.00000,20
11185,1,block_1,7,free_view,18,11,451069,514401,1,1656920233870,739.129214,434.455687,1656920233859,1.00000,20
11186,1,block_1,7,free_view,18,11,451069,514401,1,1656920233925,803.028435,459.884101,1656920233892,1.00000,20

In [4]:
# # lb_gaze = lb_gaze.loc[lb_gaze['Trial_Nr'] == 18]

# fig, ax = plt.subplots(1, figsize=(12, 6))
# fig.patch.set_facecolor('white')
# labvance_start = lb_gaze.time_lb.values[0]

# el_gaze =el_gaze.loc[el_gaze['Time'] > labvance_start]
# df_blinks_el = df_blinks_el.loc[df_blinks_el['Time'] > labvance_start]
# df_blinks_el['data_loss'] = 0

# lb_gaze['t_from_0'] = lb_gaze['time_lb'].diff().cumsum().fillna(0)
# df_blinks_el['t_from_0'] = df_blinks_el['Time'].diff().cumsum().fillna(0)
# # el_gaze_since_Labvanced
# # plt.scatter(el_gaze.Time, el_gaze.X, color = 'red', s=5, label='Good Data Eyelink')
# plt.scatter(lb_gaze.t_from_0, lb_gaze.c, color = 'blue', s=5, label='Labvanced Confidence')
# plt.scatter(df_blinks_el.t_from_0, df_blinks_el.data_loss, s=10, color = 'red', label='Blinks/Data Loss')
# # plt.scatter(lb_gaze.time_lb, lb_gaze.X_lb, color = 'blue', s=5, label='Labvanced')
# ax.set_title('LAST TRIAL Gaze Data (X-coordinations) from participant = 1', fontsize=21)
# ax.set_ylabel('Confidence Level',fontsize=22)
# ax.set_xlabel('Time (seconds)',fontsize=20)

# #     ax.legend(fontsize="x-large", loc='lower right') # using a named size
# ax.grid(linewidth = 0.4)
# ax.legend()
# ax.grid()
# plt.plot()

In [5]:
df_eyelink_raw

              Start            End  Participant_Nr
0     1643102855667  1643102855717               1
1     1643102857051  1643102857093               1
2     1643102858319  1643102858783               1
3     1643102861988  1643102862068               1
4     1643102865374  1643102865770               1
...             ...            ...             ...
8110  1656920244765  1656920244867              20
8111  1656920245327  1656920245441              20
8112  1656920247572  1656920247872              20
8113  1656920248490  1656920248642              20
8114  1656920249244  1656920249252              20

[8115 rows x 3 columns]

In [6]:
def changeToVisualDegrees(df):
    from math import atan2, degrees
    h = 21 # Monitor height in cm
    l = 42 # Montir length in cm
    d = 60 # Distance between monitor and participant in cm
    ver = 900 # Vertical resolution of the monitor
    hor = 1440
    # Calculate the number of degrees that correspond to a single pixel. This will
    # generally be a very small value, something like 0.03.
    deg_per_px = degrees(atan2(.5*h, d)) / (.5*ver)
    df[["X_lb","Y_lb","X_el","Y_el"]] = df[["X_lb","Y_lb","X_el","Y_el"]]*deg_per_px
    print('%s degrees correspond to a single pixel horizontal' % deg_per_px)
changeToVisualDegrees(df)

0.0220583233481149 degrees correspond to a single pixel horizontal

In [7]:
df

,index,time_lb,Block_Nr,Block_Name,Task_Nr,Task_Name,Trial_Nr,Trial_Id,Exp_Subject_Id,Rec_Session_Id,Session_Nr,timestamp,X_lb,Y_lb,c,Participant_Nr_x,X_el,Y_el,Tracker_Time,Participant_Nr_y
0,0,1643104412839,1,block_1,7,free_view,1,17,361162,401562,1,1643104412867,14.207223,10.022144,1.00000,1,16.087135,9.339494,2115212.0,1.0
1,1,1643104412872,1,block_1,7,free_view,1,17,361162,401562,1,1643104412885,16.641919,10.512644,1.00000,1,16.051842,9.368170,2115244.0,1.0
2,2,1643104412906,1,block_1,7,free_view,1,17,361162,401562,1,1643104412942,15.212826,9.135067,1.00000,1,16.035298,9.328465,2115278.0,1.0
3,3,1643104412971,1,block_1,7,free_view,1,17,361162,401562,1,1643104412988,16.352261,10.414556,1.00000,1,16.115811,9.342803,2115344.0,1.0
4,4,1643104413004,1,block_1,7,free_view,1,17,361162,401562,1,1643104413021,16.297512,10.984348,1.00000,1,16.099267,9.324053,2115376.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25468,1580,1656920233760,1,block_1,7,free_view,18,11,451069,514401,1,1656920233778,15.553181,11.252027,0.99797,20,18.436347,6.323018,3805646.0,20.0
25469,1581,1656920233793,1,block_1,7,free_view,18,11,451069,514401,1,1656920233813,15.958968,9.908292,1.00000,20,18.328261,6.103538,3805678.0,20.0
25470,1582,1656920233826,1,block_1,7,free_view,18,11,451069,514401,1,1656920233845,17.012860,10.282591,1.00000,20,18.394436,6.189566,3805712.0,20.0
25471,1583,1656920233859,1,block_1,7,free_view,18,11,451069,514401,1,1656920233870,16.303951,9.583364,1.00000,20,19.824918,6.340665,3805744.0,20.0
25472,1584,1656920233892,1,block_1,7,free_view,18,11,451069,514401,1,1656920233925,17.713461,10.144272,1.00000,20,20.612400,6.666025,3805778.0,20.0

In [8]:
blinks = []
df_blinks = pd.DataFrame()
df_no_b = pd.DataFrame()
for index, row in df_eyelink_raw.iterrows():
    blink_offset = row['End']
    blink_onset = row['Start']
    within_blinks = df.loc[(df.time_lb <= blink_offset) & (df.time_lb >= blink_onset)]
    blinks.append(within_blinks)

df_blinks = pd.concat(blinks, axis=0, ignore_index=False)
# df.drop(df_blinks.index, inplace=True)

In [17]:
def lagCrossCorr(df):
    means_c_arr = []
    for i in range(10, 501, 10):
        df_changed = pd.DataFrame()
        # add 1 ms for each interation
        print('Timestamp before iteration ' + str(df['time_lb'].values[0]))
        df['time_lb'] = df['time_lb_changed'] + i 
        print('Timestamp before after ' + str(df['time_lb_changed'].values[0]))
        # Compute blinks with new time value (+1):
        blinks = []
        df_blinks = pd.DataFrame()
        df_no_b = pd.DataFrame()
        
        for index, row in df_eyelink_raw.iterrows():
            # Create onset and offset time
            blink_offset = row['End']
            blink_onset = row['Start']
            # Take value between onset and offset to establish timestamps for blinks
            within_blinks = df_changed.loc[(df.time_lb_changed <= blink_offset) & (df.time_lb_changed >= blink_onset)]
            blinks.append(within_blinks)
        # Create DataFrame from blinks
        df_blinks = pd.concat(blinks, axis=0, ignore_index=False)
        # Take mean value of the C
        print(df_blinks)
        break
        mean_c = df_blinks.c.mean()
        
        # Create arr with means
        means_c_arr.append(mean_c)
        print(means_c_arr)
    return means_c_arr

In [18]:
means_c_arr = lagCrossCorr(df)

Timestamp before iteration 1643104413199
Timestamp before after 1643104413209
             time_lb
465    1643104439280
844    1643104470823
845    1643104470856
846    1643104470889
1696   1643114378299
...              ...
25134  1656920220097
25135  1656920220130
25470  1656920234196
25471  1656920234229
25472  1656920234262

[270 rows x 1 columns]

In [ ]:
df_blinks

In [ ]:
df_no_b_c = df.c.mean()
print('NO BLINKS Grouped by - ' + str(df.groupby('Participant_Nr_x').c.mean()))
print('over all participants M=' + str(df_no_b_c) + ' SD= ' + str(df.c.std()))

In [ ]:
df

In [ ]:
df_blinks

In [ ]:
df_blinks_c = df_blinks.c.mean()
df_blinks_c

In [ ]:
print('BLINKS Grouped by - ' + str(df_blinks.groupby('Participant_Nr_x').c.mean()))
print('over all participants M=' + str(df_blinks.c.mean()) + ' SD= ' + str(df_blinks.c.std()))

In [ ]:
df.head(835)

In [ ]:
participants = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
def plottingBlinks(subject, trial):    
    df_trial = df_blinks
    df_p = df
    df_p['t_from_0'] = df_p['time_lb'].diff().cumsum().fillna(0)
    df_trial['t_from_0'] = df_trial['time_lb'].diff().cumsum().fillna(0)
    df_trial = df_trial.loc[(df_trial['Participant_Nr_x']== subject)]
    df_p = df_p.loc[(df_p['Participant_Nr_x']== subject)]
    df_p = df_p.loc[df_p['Trial_Nr']== trial]
    df_trial = df_trial.loc[df_trial['Trial_Nr']==trial]
    print(df_trial)
#     print(df_trial)
#     df_p = df_p.loc[(df_p['Participant_Nr_x']== subject)]
    
    fig, ax = plt.subplots(1, figsize=(12, 6))
    fig.patch.set_facecolor('white')
    plt.scatter(df_p.time_lb, df_p.X_lb, color = 'blue', s=5, label='Labvanced')
    plt.scatter(df_p.time_lb, df_p.X_el, color = 'red', s=5, label='Eyelink')
    df_trial['data_loss'] = 0
    # BLinks
#     plt.plot(df_p.time_lb, df_p.c, color = 'blue', label='Labvanced Confidence')
#     plt.scatter(df_trial.time_lb, df_trial.data_loss, color = 'red', label='Eyelink Events Detected')
    
#     plt.scatter(df_p.time_lb, df_p.c, color = 'blue', s=15, label='Labvanced Confidence')
#     plt.scatter(df_trial.time_lb, df_trial.data_loss,s=15, color = 'red', label='Eyelink Events Detected')
    # plt.scatter(lb_gaze.time_lb, lb_gaze.X_lb, color = 'blue', s=5, label='Labvanced')
    ax.set_title('Confidence level and data loss from participant = 1', fontsize=21)
    ax.set_ylabel('Confidence Level',fontsize=22)
    ax.set_xlabel('Time Miliseconds',fontsize=20)

    #     ax.legend(fontsize="x-large", loc='lower right') # using a named size
    ax.grid(linewidth = 0.4)
    ax.legend()
    ax.grid()

#     ax.legend(fontsize="x-large", loc='lower right') # using a named size
    ax.grid(linewidth = 0.4)
    ax.legend()
    ax.grid()
    # ax.set_ylim(-10,25)
    # plt.gcf().autofmt_xdate()
    plt.show()
for i in range(len(participants)):
    plottingBlinks(i, 10)