In [1]:
# Import many dataFrame for the Algorithm Comparison:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import cm
from matplotlib.lines import Line2D
from scipy import stats
import glob
import os

In [2]:
i = 10

In [3]:
counter = 11
# for files in sorted(glob.glob("../../data/lb_data/timeseries_data/*.csv"),key=os.path.getmtime):
#     lb_data = files  
# for files in sorted(glob.glob("../../data/el_data/*.csv"),key=os.path.getmtime):
#     el_data = files  
#     counter = counter + 1
#     # print(counter)
# for i in range(3,counter):
df_lb = pd.read_csv('../data/lb_data/fixations_data/p' + str(i) + '_fixations.csv')
df_lb_trial = pd.read_csv('../data/lb_data/lb_trial_pp/p' + str(i) + '_trial_pp.csv')
# df_lb_trial = pd.read_csv('../data/lb_data/trial_data/p' + str(i) + '_trials.csv')
df_lb_trial.head()

df_lb = df_lb.rename({'value': 'x', 'Unnamed: 11': 'y','Unnamed: 12': 'dur','Unnamed: 13': 'ts','Unnamed: 14': 'tf','Unnamed: 15': 'disp'}, axis='columns')
df_lb = df_lb[df_lb['Task_Name'] == 'large_grid']
df_lb = df_lb.sort_values(by ='timestamp' )
df_lb["ts"] = pd.to_numeric(df_lb["ts"],downcast='integer')
df_lb["tf"] = pd.to_numeric(df_lb["tf"],downcast='integer')
df_lb["x"] = pd.to_numeric(df_lb["x"],downcast='integer')
df_lb["y"] = pd.to_numeric(df_lb["y"],downcast='integer') 
df_lb = df_lb.dropna()

df_lb

# # Changing index for the synchronization


# df_lb = df_lb.set_index('ts')
# df_lb_trial = df_lb_trial.set_index('target_offset')
# # Delete all fixation after offfset and find closest fixation beginning

# # df_lb_trial = df_lb_trial.set_index('target_offset')
# #HERE GROUP FOR TRIAL NR AND TAKE ONLY FIXATIONS WHICH TIME START (TS) VALUE IS LOWER THEN TIMEOFFSET FROM TRIAL DATA.
# # THEN FIND THE CLOSEST VALUE TO THE REMAINING FIXATIONS FOR TS, 
# # THEN I WILL HAVE ONLY FIXATION WHICH START IS CLOSEST TO OFFEST BUT NOT AFTER
# df_lastFix = pd.DataFrame([df_lb.iloc[df_lb.index.get_loc(t, method='nearest')] for t in df_lb_trial.index])
# df_lastFix["x"] = df_lastFix['x'].apply(lambda x: int('%.0f' % x))
# df_lastFix["y"] = df_lastFix['y'].apply(lambda x: int('%.0f' % x))
# df_lastFix["disp"] = pd.to_numeric(df_lastFix["disp"])
# df_lastFix = df_lastFix.reset_index()
# df_lb_trial = df_lb_trial.reset_index()
# #SETUP COLORS FOR THE GRAPHS
# df_lastFix['color'] = pd.Series(dtype='int')
# df_lastFix.loc[(df_lastFix.disp < 50), 'color'] = "Green"
# df_lastFix.loc[(df_lastFix.disp > 50) & (df_lastFix.disp < 100), 'color'] = "Yellow"
# df_lastFix.loc[(df_lastFix.disp >= 100) & (df_lastFix.disp < 500), 'color'] = "Red"

# # Caluclate The Euclidan Distance

# x1 = df_lastFix.x
# # x1
# x2 = df_lb_trial.targetX
# # x2
# y1 = df_lastFix.y
# # y1
# y2 = df_lb_trial.targetY
# # y2
# d2 = np.square( x2 - x1 )  + np.square( y2 - y1 ) 


# distances = np.sqrt( d2 )
# df_lastFix['distance'] = distances

# fig, ax = plt.subplots(1, figsize=(9,7))
# plt.scatter(df_lb_trial.targetX, df_lb_trial.targetY, marker='o', c=df_lastFix.color, s=df_lastFix.disp)
# plt.gca().invert_yaxis()
# plt.title('LABVANCED: Participant number - '+str(i)+' last fixations centroid grupped around the 56 targets in the Large Gird Paradigm, showin in the different colours the Dispersion in pixels \n Dispersion less then 50 - GREEN \n Dispersion between 50 and 100 PIXELS - YELLOW \n Dispersion more then 100 PIXELS - RED')
# plt.xlabel('x coordinates in pixel units')
# plt.ylabel('y coordinates in pixel units')
# plt.legend()
# plt.grid(True)
# plt.savefig('./LB_Fixations_Graphs/' + str(i) + 'LB_lf_DistanceLine.jpg')
# plt.show()
# def distanceToTargetPlot(frows,lrows):
#     fig, ax = plt.subplots(1, figsize=(16,10))
#     plt.gca().invert_yaxis()
#     t = df_lastFix.loc[frows:lrows]
#     t1 = df_lb_trial.loc[frows:lrows]

#     point1 = [t1.targetX, t1.targetY]
#     point2 = [t.x, t.y]

#     x_values = [point1[0], point2[0]]

#     y_values = [point1[1], point2[1]]



# #     plt.plot(t.x, t.y, color='pink', linestyle = 'dashed')
#     plt.plot(x_values, y_values, color='blue')
#     plt.scatter(t1.targetX, t1.targetY, marker='+', c='Black', s=100)
#     plt.scatter(t.x, t.y, marker='^', s=100)
#     plt.title('LABVANCED DATA: Patricipant ' + str(i) + ' with the fixation centroid grupped around the 56 target in the Large Gird Paradigm',fontsize=20)
#     plt.xlabel('x coordinates in pixel units',fontsize=12)
#     plt.ylabel('y coordinates in pixel units',fontsize=12)
#     plt.savefig('./LB_Fixations_Graphs/'+ str(i) + 'LB_lf_DistanceLine.jpg')
#     plt.grid(True)
#     plt.show()
# distanceToTargetPlot(0,56)

# def precisionPlot(participant_number):   

#     df_lastFix['colorDist'] = pd.Series(dtype='int')

#     df_lastFix.loc[df_lastFix.distance < 100, 'colorDist'] = "Green"
#     df_lastFix.loc[(df_lastFix.distance > 100) & (df_lastFix.distance < 150), 'colorDist'] = "Yellow"
#     df_lastFix.loc[(df_lastFix.distance >= 150) & (df_lastFix.distance < 100000000), 'colorDist'] = "Red"


#     fig, ax = plt.subplots(1, figsize=(16,10))
#     plt.scatter(df_lb_trial.targetX, df_lb_trial.targetY, marker='o', c=df_lastFix.colorDist, s=df_lastFix.distance)
#     plt.gca().invert_yaxis()
#     plt.title( 'LABVANCED DATA: results of participant ' + str(participant_number) +' with the fixation centroid grupped around the 56 target in the Large Gird Paradigm, showin in the different colours the distance in pixel \n Distance less then 100 - GREEN \n Distance between 100 and 150 PIXELS - YELLOW \n Distance more then 150 PIXELS - RED')
#     plt.xlabel('x coordinates in pixel units')
#     plt.ylabel('y coordinates in pixel units')
#     plt.grid(True)
#     plt.savefig('./LB_Fixations_Graphs/'+ str(i) + 'LB_lf_DistanceTarget.jpg')
#     plt.show()
# precisionPlot(i)

# df_lastFix.to_csv('../data/lb_data/last_fixation_data/' + str(i) + '_lb_fix.csv', index = False)

,Block_Nr,Block_Name,Task_Nr,Task_Name,Trial_Nr,Trial_Id,Exp_Subject_Id,Rec_Session_Id,Session_Nr,timestamp,x,y,dur,ts,tf,disp
620,1,block_1,3,large_grid,1,20,374007,418186,1,1645009086757,1096.979735,817.693922,168.0,1.645009e+12,1.645009e+12,26.291808
621,1,block_1,3,large_grid,1,20,374007,418186,1,1645009086966,725.045685,482.913109,132.0,1.645009e+12,1.645009e+12,50.012859
622,1,block_1,3,large_grid,1,20,374007,418186,1,1645009087259,328.716263,708.205584,136.0,1.645009e+12,1.645009e+12,45.033235
623,1,block_1,3,large_grid,1,20,374007,418186,1,1645009087687,330.768787,711.831060,330.0,1.645009e+12,1.645009e+12,42.748106
624,1,block_1,3,large_grid,1,20,374007,418186,1,1645009087965,358.186024,780.186827,232.0,1.645009e+12,1.645009e+12,43.983652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1184,1,block_1,3,large_grid,56,25,374007,418186,1,1645009488466,300.652912,672.500833,231.0,1.645009e+12,1.645009e+12,34.455152
1185,1,block_1,3,large_grid,56,25,374007,418186,1,1645009488870,350.110926,693.509509,232.0,1.645009e+12,1.645009e+12,32.173455
1186,1,block_1,3,large_grid,56,25,374007,418186,1,1645009489470,374.877040,709.847364,267.0,1.645009e+12,1.645009e+12,28.179223
1187,1,block_1,3,large_grid,56,25,374007,418186,1,1645009489825,333.128589,698.177443,245.0,1.645009e+12,1.645009e+12,35.147318
1188,1,block_1,3,large_grid,56,25,374007,418186,1,1645009490164,355.805163,607.924984,267.0,1.645009e+12,1.645009e+12,59.221479

In [4]:
df_lb_trial = df_lb_trial[df_lb_trial['Task_Name'] == 'large_grid']
df_lb_trial.button_pressed = df_lb_trial.button_pressed.apply(lambda x: int('%.0f' % x))
df_lb_trial["targetX"] = pd.to_numeric(df_lb_trial["targetX"],downcast='integer')
df_lb_trial["targetY"] = pd.to_numeric(df_lb_trial["targetY"],downcast='integer') 

df_lb["ts"] = df_lb['ts'].apply(lambda x: int('%.0f' % x))
df_lb["tf"] = df_lb['tf'].apply(lambda x: int('%.0f' % x))


df_lb_trial['target_offset'] = df_lb_trial['StartFrame'] + df_lb_trial['target_visibility_afterTime']
df_lb_trial['target_offset'] = df_lb_trial['target_offset'].apply(lambda x: int('%.0f' % x))
df_lb_trial.head()

,Unnamed: 0,index,Rec_Session_Id,Block_Nr,Block_Name,Task_Nr,Task_Name,Trial_Nr,Trial_Id,button_pressed,...,StartFrame,target_visibility_afterTime,targetX,targetY,time_offset_beep,time_sound_beep,trial_error,videoRecordTime,reactionTimeCalc,target_offset
0,1,27,418186,1,block_1,3,large_grid,2,24,1645009113005,...,1.645009e+12,2479.0,120,200,NaN,NaN,56.273472,NaN,400.0,1645009112625
1,2,28,418186,1,block_1,3,large_grid,3,14,1645009116583,...,1.645009e+12,2464.0,120,800,NaN,NaN,56.273472,NaN,359.0,1645009116231
2,3,29,418186,1,block_1,3,large_grid,4,43,1645009120006,...,1.645009e+12,2358.0,120,100,NaN,NaN,56.273472,NaN,297.0,1645009119721
3,4,30,418186,1,block_1,3,large_grid,5,4,1645009123502,...,1.645009e+12,2450.0,720,800,NaN,NaN,56.273472,NaN,291.0,1645009123227
4,5,31,418186,1,block_1,3,large_grid,6,30,1645009126758,...,1.645009e+12,2209.0,1120,700,NaN,NaN,56.273472,NaN,281.0,1645009126485

In [5]:
# Loop over the trials
df_lb_trial['offsetFixation_idx'] = -9999
for index, row in df_lb_trial.iterrows():
    target_offset = row['target_offset']
    
    beforePreviousFix = df_lb.loc[df_lb.ts < target_offset]
    lastfixation = beforePreviousFix.iloc[-1]
    nextfixation = df_lb.loc[beforePreviousFix.index[-1] + 1]
    df_lb_trial.loc[index, "offsetFixation_idx"] = beforePreviousFix.index[-1]

In [6]:
df_lb_trial = df_lb_trial.set_index("offsetFixation_idx")
df_lb_trial.head()

,Unnamed: 0,index,Rec_Session_Id,Block_Nr,Block_Name,Task_Nr,Task_Name,Trial_Nr,Trial_Id,button_pressed,...,StartFrame,target_visibility_afterTime,targetX,targetY,time_offset_beep,time_sound_beep,trial_error,videoRecordTime,reactionTimeCalc,target_offset
offsetFixation_idx,,,,,,,,,,,,,,,,,,,,,
691,1,27,418186,1,block_1,3,large_grid,2,24,1645009113005,...,1.645009e+12,2479.0,120,200,NaN,NaN,56.273472,NaN,400.0,1645009112625
701,2,28,418186,1,block_1,3,large_grid,3,14,1645009116583,...,1.645009e+12,2464.0,120,800,NaN,NaN,56.273472,NaN,359.0,1645009116231
711,3,29,418186,1,block_1,3,large_grid,4,43,1645009120006,...,1.645009e+12,2358.0,120,100,NaN,NaN,56.273472,NaN,297.0,1645009119721
720,4,30,418186,1,block_1,3,large_grid,5,4,1645009123502,...,1.645009e+12,2450.0,720,800,NaN,NaN,56.273472,NaN,291.0,1645009123227
728,5,31,418186,1,block_1,3,large_grid,6,30,1645009126758,...,1.645009e+12,2209.0,1120,700,NaN,NaN,56.273472,NaN,281.0,1645009126485

In [7]:
df_lb

,Block_Nr,Block_Name,Task_Nr,Task_Name,Trial_Nr,Trial_Id,Exp_Subject_Id,Rec_Session_Id,Session_Nr,timestamp,x,y,dur,ts,tf,disp
620,1,block_1,3,large_grid,1,20,374007,418186,1,1645009086757,1096.979735,817.693922,168.0,1645009086537,1645009086705,26.291808
621,1,block_1,3,large_grid,1,20,374007,418186,1,1645009086966,725.045685,482.913109,132.0,1645009086772,1645009086904,50.012859
622,1,block_1,3,large_grid,1,20,374007,418186,1,1645009087259,328.716263,708.205584,136.0,1645009087069,1645009087205,45.033235
623,1,block_1,3,large_grid,1,20,374007,418186,1,1645009087687,330.768787,711.831060,330.0,1645009087304,1645009087634,42.748106
624,1,block_1,3,large_grid,1,20,374007,418186,1,1645009087965,358.186024,780.186827,232.0,1645009087667,1645009087899,43.983652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1184,1,block_1,3,large_grid,56,25,374007,418186,1,1645009488466,300.652912,672.500833,231.0,1645009488145,1645009488376,34.455152
1185,1,block_1,3,large_grid,56,25,374007,418186,1,1645009488870,350.110926,693.509509,232.0,1645009488576,1645009488808,32.173455
1186,1,block_1,3,large_grid,56,25,374007,418186,1,1645009489470,374.877040,709.847364,267.0,1645009489140,1645009489407,28.179223
1187,1,block_1,3,large_grid,56,25,374007,418186,1,1645009489825,333.128589,698.177443,245.0,1645009489507,1645009489752,35.147318
1188,1,block_1,3,large_grid,56,25,374007,418186,1,1645009490164,355.805163,607.924984,267.0,1645009489852,1645009490119,59.221479

In [11]:
df_full = pd.merge(df_lb, df_lb_trial, left_index=True, right_index=True)
# df_full = df_full.drop(columns=['time_lb'])
# df_full = df_full.reset_index()

In [16]:
df_full

AttributeError: 'DataFrame' object has no attribute 'dist'

In [127]:
df_lb.head()

,Block_Nr,Block_Name,Task_Nr,Task_Name,Trial_Nr,Trial_Id,Exp_Subject_Id,Rec_Session_Id,Session_Nr,timestamp,x,y,dur,ts,tf,disp
620,1,block_1,3,large_grid,1,20,374007,418186,1,1645009086757,1096.979735,817.693922,168.0,1645009086537,1645009086705,26.291808
621,1,block_1,3,large_grid,1,20,374007,418186,1,1645009086966,725.045685,482.913109,132.0,1645009086772,1645009086904,50.012859
622,1,block_1,3,large_grid,1,20,374007,418186,1,1645009087259,328.716263,708.205584,136.0,1645009087069,1645009087205,45.033235
623,1,block_1,3,large_grid,1,20,374007,418186,1,1645009087687,330.768787,711.831060,330.0,1645009087304,1645009087634,42.748106
624,1,block_1,3,large_grid,1,20,374007,418186,1,1645009087965,358.186024,780.186827,232.0,1645009087667,1645009087899,43.983652